### ISSUE TITLE
422 Client error

### ISSUE THREAD

**Issue by j-born** [etlweather/gaucho#10]
I try to upgrade service:

`docker run --rm -e CATTLE_ACCESS_KEY=**** -e CATTLE_SECRET_KEY=*** -e CATTLE_URL=http://***/v1/projects/1a11 etlweather/gaucho upgrade 1s186 --imageUuid docker:***:1.0.80 --auto_complete`

but

```
Traceback (most recent call last):
  File "/app/gaucho", line 274, in <module>
    baker.run()
  File "/usr/local/lib/python2.7/site-packages/baker.py", line 888, in run
New Image: docker:***:1.0.80
    value = self.apply(*self.parse(argv), instance=instance)
  File "/usr/local/lib/python2.7/site-packages/baker.py", line 866, in apply
    return cmd.fn(*newargs, **newkwargs)
  File "/app/gaucho", line 157, in upgrade
    post(current_service_config['actions']['upgrade'], upgrade_strategy)
  File "/app/gaucho", line 27, in post
    r.raise_for_status()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: status code 422 for url:
```

**Comment by etlweather** [comment]
What version of Rancher are you running? But I think the problem there is the `CATTLE_URL` variable. It should be: `http://***/v1` - you have too much there.

**Comment by j-born** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/24295069/21987720/aaf6ec74-dc15-11e6-807e-f3d1ee4dc7af.png)

http://***/v1 - i hide the url for this post )

**Comment by etlweather** [comment]
Ok, I haven't tried with v1.2.1, I'm still at v1.1.2 but in theory that shouldn't be a problem. On the URL, I meant, you have `/v1/projects/1a11`. The expected URL is `http://***/v1` (nothing after `/v1`).

**Comment by j-born** [comment]
I have two containers which i want to update, one of them upgrade good all time, but second failed everytime

**Comment by j-born** [comment]
I try change URL to "nothing after /v1"

```
[15:26:18][Step 8/8] Traceback (most recent call last):
[15:26:18][Step 8/8] New Image: docker:***/app-client-view:1.0.21
[15:26:18][Step 8/8]   File "/app/gaucho", line 274, in <module>
[15:26:18][Step 8/8]     baker.run()
[15:26:18][Step 8/8]   File "/usr/local/lib/python2.7/site-packages/baker.py", line 888, in run
[15:26:18][Step 8/8]     value = self.apply(*self.parse(argv), instance=instance)
[15:26:18][Step 8/8]   File "/usr/local/lib/python2.7/site-packages/baker.py", line 866, in apply
[15:26:18][Step 8/8]     return cmd.fn(*newargs, **newkwargs)
[15:26:18][Step 8/8]   File "/app/gaucho", line 157, in upgrade
[15:26:18][Step 8/8]     post(current_service_config['actions']['upgrade'], upgrade_strategy)
[15:26:18][Step 8/8]   File "/app/gaucho", line 27, in post
[15:26:18][Step 8/8]     r.raise_for_status()
[15:26:18][Step 8/8]   File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 893, in raise_for_status
[15:26:18][Step 8/8]     raise HTTPError(http_error_msg, response=self)
[15:26:18][Step 8/8] requests.exceptions.HTTPError: 422 Client Error: status code 422 for url: http://***/v1/services/1s168/?action=upgrade
[15:26:19][Step 8/8] Process exited with code 1
```

**Comment by j-born** [comment]
Really we have more than 10 services which we try to upgrade with the tool.
And I noticed a pattern with problem.
If service have service ID great than 100 (for example 1s168) upgrade failed with the error (see above), but if less than 100 (example 1s18) everything OK.

I understand that sounds strange, it can be helpfull

**Comment by etlweather** [comment]
I'll have to set up Rancher v1.2+ to see. My upgrades never fail like that and most of my services have an ID greater than 100. Rancher version is the only major difference I see.

**Comment by j-born** [comment]
I can't debug python code :(
I hope you fix it, we want to use the tool :)

Thank you.

**Comment by etlweather** [comment]
Question: are these services all in the same environment?

**Comment by j-born** [comment]
Yes, it is in the same environment.
```
{
   "accountId": "1a11",
   "actions": {
      "addservicelink": "http://***/v1/services/1s168/?action=addservicelink",
      "deactivate": "http://***/v1/services/1s168/?action=deactivate",
      "remove": "http://***/v1/services/1s168/?action=remove",
      "removeservicelink": "http://***/v1/services/1s168/?action=removeservicelink",
      "restart": "http://***/v1/services/1s168/?action=restart",
      "setservicelinks": "http://***/v1/services/1s168/?action=setservicelinks",
      "update": "http://***/v1/services/1s168/?action=update",
      "upgrade": "http://***/v1/services/1s168/?action=upgrade"
   },
   "assignServiceIpAddress": false,
   "baseType": "service",
   "createIndex": 19,
   "created": "2016-12-29T10:05:32Z",
   "createdTS": 1483005932000,
   "currentScale": 1,
   "description": null,
   "environmentId": "1e18",
   "externalId": null,
   "fqdn": null,
   "healthState": "healthy",
   "id": "1s168",
   "instanceIds": [
      "1i1503"
   ],
   "kind": "service",
   "launchConfig": {
      "blkioWeight": null,
      "capAdd": [],
      "capDrop": [],
      "cgroupParent": null,
      "count": null,
      "cpuCount": null,
      "cpuPercent": null,
      "cpuPeriod": null,
      "cpuQuota": null,
      "cpuSet": null,
      "cpuSetMems": null,
      "cpuShares": null,
      "dataVolumes": [
         "/opt/export:/opt/export"
      ],
      "dataVolumesFrom": [],
      "dataVolumesFromLaunchConfigs": [],
      "description": null,
      "devices": [],
      "diskQuota": null,
      "dns": [],
      "dnsSearch": [],
      "domainName": "app-item-service",
      "environment": {
         "CONFIG_BRANCH": "master",
         "CONFIG_SERVER": "apps-config",
         "PASSWORD_MONGO_CLIENT": "***",
         "PASSWORD_POSTGRES_ITEM_SERVICE": "***",
         "SPRING_PROFILES_ACTIVE": "qa"
      },
      "healthInterval": null,
      "healthRetries": null,
      "healthTimeout": null,
      "hostname": null,
      "imageUuid": "docker:***:1.0.22",
      "instanceTriggeredStop": "stop",
      "ioMaximumBandwidth": null,
      "ioMaximumIOps": null,
      "ip": null,
      "ip6": null,
      "ipcMode": null,
      "isolation": null,
      "kernelMemory": null,
      "kind": "container",
      "labels": {
         "io.rancher.container.pull_image": "always"
      },
      "logConfig": {
         "config": {},
         "driver": "none",
         "type": "logConfig"
      },
      "memory": null,
      "memoryMb": null,
      "memoryReservation": null,
      "memorySwap": null,
      "memorySwappiness": null,
      "milliCpuReservation": null,
      "networkLaunchConfig": null,
      "networkMode": "managed",
      "oomScoreAdj": null,
      "pidMode": null,
      "pidsLimit": null,
      "ports": [],
      "privileged": false,
      "publishAllPorts": false,
      "readOnly": false,
      "requestedIpAddress": null,
      "shmSize": null,
      "startOnCreate": true,
      "stdinOpen": true,
      "stopSignal": null,
      "system": false,
      "tty": true,
      "type": "launchConfig",
      "user": null,
      "userdata": null,
      "usernsMode": null,
      "uts": null,
      "vcpu": 1,
      "version": "a8752bb2-2dc8-40b8-bc28-326ceca9de06",
      "volumeDriver": null,
      "workingDir": null
   },
   "lbConfig": null,
   "linkedServices": null,
   "links": {
      "account": "http://***/v1/services/1s168/account",
      "consumedbyservices": "http://***/v1/services/1s168/consumedbyservices",
      "consumedservices": "http://***/v1/services/1s168/consumedservices",
      "containerStats": "http://***/v1/services/1s168/containerstats",
      "environment": "http://***/v1/environment/1e18",
      "instances": "http://***/v1/services/1s168/instances",
      "networkDrivers": "http://***/v1/services/1s168/networkdrivers",
      "self": "http://***/v1/services/1s168",
      "serviceExposeMaps": "http://***/v1/services/1s168/serviceexposemaps",
      "serviceLogs": "http://***/v1/services/1s168/servicelogs",
      "storageDrivers": "http://***/v1/services/1s168/storagedrivers"
   },
   "metadata": {
      "io.rancher.service.hash": "e041b3c611730c5b9ebcd9e16b336a5943a97e40"
   },
   "name": "app-client-view",
   "publicEndpoints": null,
   "removed": null,
   "retainIp": true,
   "scale": 1,
   "scalePolicy": null,
   "secondaryLaunchConfigs": [],
   "selectorContainer": null,
   "selectorLink": null,
   "stackId": "1st18",
   "startOnCreate": false,
   "state": "active",
   "system": false,
   "transitioning": "no",
   "transitioningMessage": null,
   "transitioningProgress": null,
   "type": "service",
   "upgrade": {
      "inServiceStrategy": {
         "batchSize": 1,
         "intervalMillis": 2000,
         "launchConfig": {
            "blkioWeight": null,
            "capAdd": [],
            "capDrop": [],
            "cgroupParent": null,
            "count": null,
            "cpuCount": null,
            "cpuPercent": null,
            "cpuPeriod": null,
            "cpuQuota": null,
            "cpuSet": null,
            "cpuSetMems": null,
            "cpuShares": null,
            "dataVolumes": [
               "/opt/export:/opt/export"
            ],
            "dataVolumesFrom": [],
            "dataVolumesFromLaunchConfigs": [],
            "description": null,
            "devices": [],
            "diskQuota": null,
            "dns": [],
            "dnsSearch": [],
            "domainName": "app-item-service",
            "environment": {
               "CONFIG_BRANCH": "master",
               "CONFIG_SERVER": "apps-config",
               "PASSWORD_MONGO_CLIENT": "***",
               "PASSWORD_POSTGRES_ITEM_SERVICE": "***",
               "SPRING_PROFILES_ACTIVE": "qa"
            },
            "healthInterval": null,
            "healthRetries": null,
            "healthTimeout": null,
            "hostname": null,
            "imageUuid": "docker:***:1.0.22",
            "instanceTriggeredStop": "stop",
            "ioMaximumBandwidth": null,
            "ioMaximumIOps": null,
            "ip": null,
            "ip6": null,
            "ipcMode": null,
            "isolation": null,
            "kernelMemory": null,
            "kind": "container",
            "labels": {
               "io.rancher.container.pull_image": "always"
            },
            "logConfig": {
               "config": {},
               "driver": "none",
               "type": "logConfig"
            },
            "memory": null,
            "memoryMb": null,
            "memoryReservation": null,
            "memorySwap": null,
            "memorySwappiness": null,
            "milliCpuReservation": null,
            "networkLaunchConfig": null,
            "networkMode": "managed",
            "oomScoreAdj": null,
            "pidMode": null,
            "pidsLimit": null,
            "ports": [],
            "privileged": false,
            "publishAllPorts": false,
            "readOnly": false,
            "requestedIpAddress": null,
            "shmSize": null,
            "startOnCreate": true,
            "stdinOpen": true,
            "stopSignal": null,
            "system": false,
            "tty": true,
            "type": "launchConfig",
            "user": null,
            "userdata": null,
            "usernsMode": null,
            "uts": null,
            "vcpu": 1,
            "version": "a8752bb2-2dc8-40b8-bc28-326ceca9de06",
            "volumeDriver": null,
            "workingDir": null
         },
         "previousLaunchConfig": {
            "blkioWeight": null,
            "capAdd": [],
            "capDrop": [],
            "cgroupParent": null,
            "count": null,
            "cpuCount": null,
            "cpuPercent": null,
            "cpuPeriod": null,
            "cpuQuota": null,
            "cpuSet": null,
            "cpuSetMems": null,
            "cpuShares": null,
            "dataVolumes": [
               "/opt/export:/opt/export"
            ],
            "dataVolumesFrom": [],
            "dataVolumesFromLaunchConfigs": [],
            "description": null,
            "devices": [],
            "diskQuota": null,
            "dns": [],
            "dnsSearch": [],
            "domainName": "app-item-service",
            "environment": {
               "CONFIG_BRANCH": "master",
               "CONFIG_SERVER": "apps-config",
               "PASSWORD_MONGO_CLIENT": "***",
               "PASSWORD_POSTGRES_ITEM_SERVICE": "***",
               "SPRING_PROFILES_ACTIVE": "qa"
            },
            "healthInterval": null,
            "healthRetries": null,
            "healthTimeout": null,
            "hostname": null,
            "imageUuid": "docker:***:1.0.20",
            "instanceTriggeredStop": "stop",
            "ioMaximumBandwidth": null,
            "ioMaximumIOps": null,
            "ip": null,
            "ip6": null,
            "ipcMode": null,
            "isolation": null,
            "kernelMemory": null,
            "kind": "container",
            "labels": {
               "io.rancher.container.pull_image": "always"
            },
            "logConfig": {
               "config": {},
               "driver": "none",
               "type": "logConfig"
            },
            "memory": null,
            "memoryMb": null,
            "memoryReservation": null,
            "memorySwap": null,
            "memorySwappiness": null,
            "milliCpuReservation": null,
            "networkLaunchConfig": null,
            "networkMode": "managed",
            "oomScoreAdj": null,
            "pidMode": null,
            "pidsLimit": null,
            "ports": [],
            "privileged": false,
            "publishAllPorts": false,
            "readOnly": false,
            "requestedIpAddress": null,
            "shmSize": null,
            "startOnCreate": true,
            "stdinOpen": true,
            "stopSignal": null,
            "system": false,
            "tty": true,
            "type": "launchConfig",
            "user": null,
            "userdata": null,
            "usernsMode": null,
            "uts": null,
            "vcpu": 1,
            "version": "8b77d5e7-f135-4a51-a54b-6a41053a571a",
            "volumeDriver": null,
            "workingDir": null
         },
         "previousSecondaryLaunchConfigs": [],
         "secondaryLaunchConfigs": [],
         "startFirst": false,
         "type": "inServiceUpgradeStrategy"
      },
      "toServiceStrategy": null,
      "type": "serviceUpgrade"
   },
   "uuid": "b0b54512-74e3-42cb-86f6-1868c4fd7488",
   "vip": null
}
```

**Comment by etlweather** [comment]
@j-born  are you able to check the rancher server's logs to see if anything useful show up there to tell us what's going on?

**Comment by j-born** [comment]
@etlweather in server logs nothing about upgrade
I try
```
docker run --rm \
-e CATTLE_ACCESS_KEY=*** \
-e CATTLE_SECRET_KEY=*** \
-e CATTLE_URL=http://***/v1 \
etlweather/gaucho upgrade 1s168 \
--imageUuid docker:***:1.0.25 \
--auto_complete;
```

**Comment by j-born** [comment]
May be i can enable debug mode and sent to you result? )

**Comment by etlweather** [comment]
Not sure which debug, but sure. It can't hurt. Whatever info you can find will help.

**Comment by j-born** [comment]
I debug this code with my python friend :)
Rancher answer with json:
```
{
  "id": "17f6b998-b168-4b63-acf9-b08cde3153e3",
  "type": "error",
  "links": {},
  "actions": {},
  "status": 422,
  "code": "InvalidOption",
  "message": null,
  "detail": null,
  "fieldName": "StartFirst option can\\'t be used for service with retainIp field set",
  "baseType": "error"
}
```

**Comment by etlweather** [comment]
Oh nice! Ok so looks like it's just a Rancher "limitation" then. So your service has a fix IP address right? The default for the `upgrade` function of Gaucho is to `startFirst`. That means it will start a new container, then take down the old one. With a fixed IP address, that is not possible, otherwise you would have a duplicate IP address.

If the fixed IP is a requirement for you, then you can do the upgrade using `--start_first=False`. This will first stop your running container and then create a new one.

I haven't tried it but I think Rancher will let you do that.

I guess it would be nice if this script would have told us that right off-the-bat... I'll log an enhancement for that aspect.
