### ISSUE TITLE
HTTP Error 422 with upgrade

### ISSUE THREAD

**Issue by FabienHenon** [etlweather/gaucho#16]
I'm trying to upgrade my service with a new image but I get a 422 status code during upgrade.

Here is the docker command I'm using:

```
docker run --rm -it -e RANCHER_URL=http://myrancher.fr:8080/v1 -e RANCHER_ACCESS_KEY=<access_key> -e RANCHER_SECRET_KEY=<secret_key> etlweather/gaucho upgrade 1s28 --imageUuid=myrancherrepo:5000/project-img:latest
```

And here is the response I get:

```
New Image: myrancherrepo:5000/project-img:latest
Traceback (most recent call last):
  File "/app/gaucho", line 318, in <module>
    baker.run()
  File "/usr/local/lib/python2.7/site-packages/baker.py", line 888, in run
    value = self.apply(*self.parse(argv), instance=instance)
  File "/usr/local/lib/python2.7/site-packages/baker.py", line 866, in apply
    return cmd.fn(*newargs, **newkwargs)
  File "/app/gaucho", line 157, in upgrade
    post(current_service_config['actions']['upgrade'], upgrade_strategy)
  File "/app/gaucho", line 27, in post
    r.raise_for_status()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: status code 422 for url: http://myrancher.fr:8080/v1/services/1s28/?action=upgrade
```

When I'm accessing this url (`http://myrancher.fr:8080/v1/services/1s28/?action=upgrade`) via `GET` method I can see the details of my service correctly.

What do you think is wrong?

I'm using Rancher 1.4.1

**Comment by FabienHenon** [comment]
Actually this is not an issue. This was because I didn't add the `docker:` prefix to the image. Sorry for that
